package logger

type Logger interface {
	Debug(...any)
	Info(...any)
	Warn(...any)
	Error(...any)
	DPanic(...any)
	Panic(...any)
	Fatal(...any)
	Debugf(string, ...any)
	Infof(string, ...any)
	Warnf(string, ...any)
	Errorf(string, ...any)
	DPanicf(string, ...any)
	Panicf(string, ...any)
	Fatalf(string, ...any)
	Debugw(string, ...any)
	Infow(string, ...any)
	Warnw(string, ...any)
	Errorw(string, ...any)
	DPanicw(string, ...any)
	Panicw(string, ...any)
	Fatalw(string, ...any)
	Debugln(...any)
	Infoln(...any)
	Warnln(...any)
	Errorln(...any)
	DPanicln(...any)
	Panicln(...any)
	Fatalln(...any)
}
