version: '3.7'

services:
  cache:
    image: redis:latest

  access:
    container_name: go-iot-access-service
    build: .
    working_dir: /app
    command: "go run -race -gcflags=\"-m -m\" ./cmd/access/main.go"
    environment:
      - APP_ENV=dev
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - "6060:6060"
      - "80:80"
    depends_on:
      - cache
    networks:
      4suites:
        aliases:
          - iot_access_service-app
  iot:
    container_name: go-iot-service-app
    build: .
    working_dir: /app
    command: "go run -race -gcflags=\"-m -m\" ./cmd/iot/main.go"
    environment:
      - APP_ENV=dev
    volumes:
      - ./:/app
    networks:
      4suites:
        aliases:
          - iot_service-app

  upgrade:
    container_name: go-iot-upgrade-service-app
    build: .
    working_dir: /app
    command: "go run -race -gcflags=\"-m -m\" ./cmd/upgrade/main.go"
    environment:
      - APP_ENV=dev
    volumes:
      - ./:/app
    networks:
      4suites:
        aliases:
          - iot_upgrade_service-app
networks:
  4suites:
    external: true
    name: 4suites
